### ISSUE TITLE
config.txt doesn't enable camera

### ISSUE THREAD

**Issue by ali1234** [pimoroni/PiratePython#14]
This prevents unicorn hd camera.py from working, event though all the necessary software is installed.

Just need to add "start_x=1" to the config.txt and maybe increase gpu_mem.

Only tested on my version of PP.

**Comment by Gadgetoid** [comment]
I wasn't sure whether to leave it permanently enabled. Reckon the benefits outweigh the drawbacks?

**Comment by ali1234** [comment]
I reckon so. You can always run out of memory if you try hard enough. Making sure that the most examples work as expected is more important I think.
